### ISSUE TITLE
scrollIntoView() removes/hides jsFiddle.net navbar

### ISSUE THREAD

**Issue by TheColorRed** [jsfiddle/jsfiddle-issues#1098]
When this basic code is ran, the header of jsFiddle.net is removed or hidden from view.

```js
document.querySelector('#green').scrollIntoView({behavior: 'smooth'})
```

```html
<div></div>
<div id="green"></div>
```

```css
body{margin:0}
div {height:100vh;}
div:nth-child(1) {background-color:red}
div:nth-child(2) {background-color:green}
```

https://jsfiddle.net/knwm8esq/
