### ISSUE TITLE
CSS4 `var` incorrectly parsed in SCSS

### ISSUE THREAD

**Issue by terrymun** [jsfiddle/jsfiddle-issues#1162]
When using CSS4 variables in SCSS mode, the compiler does not interpret the `var(--variableName)` statement correctly, and compiles it to `var("--variableName")` (note the double inverted commas). This causes fiddles to work great in CSS, but breaks when switching over to SCSS.

Example code (see [proof-of-concept fiddle here](https://jsfiddle.net/teddyrised/xy2u06u7/)):

```css
:root {
  --backgroundImage: url(https://i.imgur.com/E5sr59z.jpg);
}

body {
  background-image: var(--backgroundImage);
  background-size: cover;
  background-repeat: no-repeat;
  width: 100vw;
  height: 100vh;
}
```

When "SCSS" is select, this gets incorrectly compiled to:

```css
:root {
  --backgroundImage: url(https://i.imgur.com/E5sr59z.jpg);
}

body {
    background-image: var("--backgroundImage");  /* This line breaks */
    background-size: cover;
    background-repeat: no-repeat;
    width: 100vw;
    height: 100vh;
}
```
