### ISSUE TITLE
Better github-integration documentation

### ISSUE THREAD

**Issue by Olian04** [jsfiddle/jsfiddle-issues#1238]
I'm using the github-integration feature quite often as a way of demoing libraries. 

But as it stands the [documentation](http://doc.jsfiddle.net/use/github_read.html) is really quite poor. 
Are there any plans on updating the docs? 

Ex: 
The `demo.details` yaml file in the docs looks like this.
```yaml
Everything before the line containing only '---' will not be parsed

---
 name: The Name of the Demo
 description: Some description, please keep it in one line
 authors:
   - John Doe
   - Jan Wisniewski
 resources:
   - http://some.url.com/some/file.js
   - http://other.url.com/other_filename.css
 normalize_css: no
 ...

Everything after the line containing only '...' will not be parsed
```
However these are not all of the available options.
I only found out that you can specify the `load type` (via ` js_wrap: d`) by searching though a lot of random github repositories that happened to contain a file named: `demo.details`.
