### ISSUE TITLE
CSS fix for broken UI when hovering buttons in Firefox

### ISSUE THREAD

**Issue by joedf** [jsfiddle/jsfiddle-issues#1285]
The UI codeboxes are all shifted towards the right rendering the application unusable in firefox. This is because the "highlight" line below the buttons is a bottom border and that is rendered outside of the defined height of an element. The following fix is simple and has been tested to work flawlessly in Firefox v60.0.1 and Chrome v66.0.3359.181. There is no pull-request option here so I have posted this as an issue.

In both `dist-skeleton-dark.css` and `dist-skeleton-light.css`
```CSS
#actions .actionItem a.aiButton.selected, #actions .actionItem a.aiButton:hover {
    border-bottom: 1px solid #0084ff;
}
```
should become this
```CSS
#actions .actionItem a.aiButton.selected, #actions .actionItem a.aiButton:hover {
    border-bottom: 1px solid #0084ff;
    margin-bottom: -1px;
}
```
Simply adding `margin-bottom: -1px;` to compensate for the added element height.
