### ISSUE TITLE
Outdated SASS compiler

### ISSUE THREAD

**Issue by mindplay-dk** [jsfiddle/jsfiddle-issues#1461]
The SASS compiler doesn't accept interpolations:

```scss
@mixin bg($colors) {
  @each $name, $color in $colors {
    .bg\:#{$name} {
      background-color: $color;
    }
  }
}
```

It says "unknown word" at `$name` on line 3.

Probably a very old version that needs an update?

(Note, I did see #721 but figured the mentioned rewrite must have happened since feb'16?)
