### ISSUE TITLE
[request] CSS3 Pie hosting on fiddle.jshell.net

### ISSUE THREAD

**Issue by kuwabarahiroshi** [jsfiddle/jsfiddle-issues#195]
I'm sorry if a similar issue had already requested before, but I couldn't find such a request.

I would like to test CSS3 Pie on jsfiddle, however, it requires to be served from the same domain.
Is there any plan to host PIE.htc on fiddle.jshell.net?

So that we could write such a code as below on CSS panel:

``` css
/**
 * If Pie.htc is hosted at http://fiddle.jshell.net/path/to/PIE.htc,
 * we'll be able to test it on jsfiddle like this.
 */
.myClass {
    border-radius: 10px;
    behavior: url('/path/to/PIE.htc');
}
```
