### ISSUE TITLE
Broken SASS implementation?

### ISSUE THREAD

**Issue by ngse** [jsfiddle/jsfiddle-issues#197]
Initially I raised a bug with the SASS project, but apparently it's not a bug in the latest SASS build.  Which means either jsfiddle is using an old SASS implementation or a broken one.  Please see the ticket raised and closed with the SASS project.  I have copied the example code here for quick reference.

https://github.com/nex3/sass/issues/418

You cannot redeclare the value of a global variable inside a @mixin.

Example:

``` scss
$global: blue;

@mixin box {
  $global: red;
  color: $global; 
}

p { @include box() }
```

Expected:

``` css
p { color: red }
```

Actual:

``` css
p { blue: red; color: blue; }
```

Instead of reassigning red to the `$global` variable, it echos the value of the variable.
