### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by marcofarrugia** [jsfiddle/jsfiddle-issues#2073]
### Error code

ERRW:0.85:PU0.35:PRMS0.5:AS

### Were you logged in?

Yes

### Your username (if logged in)

testinuser

### Your HTML

```html
<!-- Add the HTML code to install the JavaScript file for the Shoelace Library here (Only the JavaScript file)-->

<header>
  <sl-button id="menu-toggle" variant="primary" circle size="medium">
    <!-- Add the hamburger icon for the menu button inside here -->
  </sl-button>
  <h1>
    <sl-icon name="controller"></sl-icon>
    Retro Gaming Hub
    <sl-icon name="controller"></sl-icon>
  </h1>

  <!-- Placeholder to balance flex -->
  <div class="spacer"></div>
</header>

<sl-drawer
  label="Main Menu"
  placement="start"
  id="menu-drawer"
  class="compact-drawer"
>
  <!-- Implement the Shoelace menu structure here -->
</sl-drawer>

<main>
  <section id="carousel-section">
    <h2>🖼️ Classic Game Gallery</h2>
    <!-- Ensure that the carousel’s required functionalities operate correctly by using the necessary attributes below: -->
    <sl-carousel id="game-carousel">
		
      <!-- content inside here to be created dynamically using JavaScript in the script.js file in the structure indicated below:-->
      <!-- 
        <sl-carousel-item>
          <div class="carousel-slide">
            <img src="image_URL" alt="Amiga computer" />
            <div class="caption">Amiga computer</div>
          </div>
        </sl-carousel-item>
-->
    </sl-carousel>
  </section>

  <section id="content-display">
    <h2>🔍 Selected Content</h2>
    <p id="dynamic-content">
      Please choose a menu option above to display info.
    </p>
  </section>
</main>

<footer>
  <p>Your Name Here &copy; 2025</p>
</footer>
```

### Your JavaScript

```javascript
// Populate the home page the initial image carousel
document.addEventListener('DOMContentLoaded', () => {
  updateCarousel(imageSets.home);
});

// Toggle drawer with burger button
const drawer = document.getElementById("menu-drawer");
const toggleBtn = document.getElementById("menu-toggle");

// Add a click event listener to the <sl-button id="menu-toggle"> that opens the <sl-drawer> when clicked.

// Menu + content area
const menu = document.getElementById("main-menu");
const content = document.getElementById("dynamic-content");
const carousel = document.getElementById("game-carousel");

// Image map for different categories
const imageSets = {
  home: [
    { src: "https://images.unsplash.com/photo-1661793422654-95210ec02652?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=dan-counsell-14TrY5kN5bQ-unsplash.jpg&w=640", alt: "Amiga computer" },
    { src: "https://images.unsplash.com/photo-1661793422648-8dc56c952ec0?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=dan-counsell-9B8EzePdkfw-unsplash.jpg&w=640", alt: "Commodore A1200" },
    { src: "https://images.unsplash.com/photo-1591462391941-8e7b33fc4604?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=ravi-palwe-4GWI7PW9_44-unsplash.jpg&w=640", alt: "Nintendo Entertainment System" },
    { src: "https://images.unsplash.com/photo-1635187834534-d1fa994fcabb?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=joey-kwok-jbIsTd7rdd8-unsplash.jpg&w=640", alt: "Arcade" },
    { src: "https://images.unsplash.com/photo-1700153849610-3e9d1030d791?ixlib=rb-4.1.0&q=85&fm=jpg&crop=entropy&cs=srgb&dl=anthony-IN3fgg8Y09U-unsplash.jpg&w=640", alt: "Sega Megadrive" }
  ],
  games: [
    { src: "https://www.retrogames.cz/games/492/DOS-gameplay.gif", alt: "The Secret of Monkey Island (1990)" },
    { src: "https://www.retrogames.cz/games/017/A26-gameplay.gif", alt: "Pac-Man" },
    { src: "https://www.retrogames.cz/games/007/NES-gameplay1.gif", alt: "Super Marco Bros 3" },
    { src: "https://www.retrogames.cz/games/068/NES-gameplay.gif", alt: "The Legend Of Zelda" },
    { src: "https://www.retrogames.cz/games/037/SMS_02.gif", alt: "Golden Axe" }
  ],
  nes: [
    { src: "https://www.retrogames.cz/games/007/NES-gameplay1.gif", alt: "Super Mario Bros 3 (NES)" },
    { src: "https://www.retrogames.cz/games/112/NES_01.gif", alt: "Metroid (NES)" },
    { src: "https://www.retrogames.cz/games/068/NES-gameplay.gif", alt: "The Legend of Zelda (NES)" }
  ],
  sega: [
    { src: "https://www.retrogames.cz/games/117/Genesis-gameplay.gif", alt: "Sonic the Hedgehog" },
    { src: "https://www.retrogames.cz/games/389/Genesis_01.gif", alt: "Streets of Rage" },
    { src: "https://www.retrogames.cz/games/037/SMS_02.gif", alt: "Golden Axe" }
  ],
  arcade: [
    { src: "https://www.retrogames.cz/games/016/A26_01.gif", alt: "Space Invaders" },
    { src: "https://www.retrogames.cz/games/017/A26-gameplay.gif", alt: "Pac-Man" },
    { src: "https://www.retrogames.cz/games/229/SMS-gameplay.png", alt: "Mortal Kombat" }
  ]
};

// Function to clear and reload new images into the carousel
function updateCarousel(images) {
  // Clear existing slides

  // Create structured slides, loading images from the images parameter array of objects.
  
}


// Handle menu selection
menu.addEventListener("sl-select", (event) => {
  const selected = event.detail.item.value;
  let message = "";
/* Depending on which menu item was selected do the following:
	 1) update the message variable with the corresponding string from the below:
			"Welcome to the Retro Gaming Hub! Explore legendary games.";
			"Check out our top picks: Pac-Man, Donkey Kong, Mario, and more!";
			"Nintendo classics include: Super Mario Bros, Metroid, Zelda.";
			"Sega Genesis legends: Sonic the Hedgehog, Streets of Rage.";
			"Arcade icons: Space Invaders, Galaga, Mortal Kombat.";
			"No information available.";
	 2) Call the updateCarousel() function with the required arguments
   */

  content.textContent = message;
  drawer.hide();
});
```

### Your CSS

```css
body {
  font-family: 'Segoe UI', sans-serif;
  background-color: #1e1e1e;
  color: #fff;
  margin: 0;
  padding: 0;
}

header {
  background-color: #111;
  padding: 1rem;
  display: flex;
  justify-content: space-between;

}

.spacer {
  width: 50px;
  /* visually balance the burger button on right */
}

h1 {
  margin: 0;
  color: #facc15;
}

footer {
  background-color: #111;
  padding: 1px;
  text-align: center;
}

main {
  padding: 2rem;
}

#carousel-section {
  margin-bottom: 2rem;
}

sl-carousel {
  max-width: 600px;
  margin: auto;
  border-radius: 10px;
  overflow: hidden;
  box-shadow: 0 0 12px rgba(255, 255, 255, 0.2);
}


.carousel-slide {
  position: relative;
  height: 100%;
  overflow: hidden;
}

.carousel-slide img {
  width: 100%;
  height: 100%;
  display: block;
}

#dynamic-content {
  background-color: #2a2a2a;
  padding: 1rem;
  border-radius: 5px;
}

.caption {
  position: absolute;
  bottom:0;
  width: 100%;
  padding: 16px;
  background-color: rgba(0, 0, 0, 0.6);
  color: #39ff14;
  font-size: 16px;
  text-align: center;
  font-family: monospace;
}
```
