### ISSUE TITLE
Para mi pequeño dudu<3

### ISSUE THREAD

**Issue by cRepEr76** [jsfiddle/jsfiddle-issues#2092]
### Error code

ERRW:1.0:K1.0

### Were you logged in?

Yes

### Your HTML

```html
<img src="https://i.pinimg.com/originals/f6/d1/97/f6d197592db0598c370cb0fdd2bdb373.gif" alt="">
  <h1>¿Podemos ser noviecitos? 💕</h1>

  <button id="yesBtn">Sí</button>
  <button id="noBtn">No</button>
```

### Your JavaScript

```javascript
const noBtn = document.getElementById('noBtn');
    const yesBtn = document.getElementById('yesBtn');

    noBtn.addEventListener('mouseover', () => {
      noBtn.style.position = 'absolute';
      noBtn.style.top = Math.random() * window.innerHeight + 'px';
      noBtn.style.left = Math.random() * window.innerWidth + 'px';
    });

    yesBtn.addEventListener('click', () => {
      alert('¡Wiiiiii! Te amo tanto mi pequeño pechocho💗✨');
    });
```

### Your CSS

```css
body {
      font-family: "Comic Sans MS", cursive;
      text-align: center;
      background-color: #fff0f5;
      padding: 50px;
    }

    img {
      width: 150px;
    }

    h1 {
      font-size: 24px;
      color: #ff4f81;
    }

    button {
      padding: 10px 20px;
      font-size: 16px;
      margin: 20px;
      cursor: pointer;
      border: none;
      border-radius: 10px;
      transition: all 0.2s ease;
    }

    #yesBtn {
      background-color: #4CAF50;
      color: white;
    }

    #noBtn {
      background-color: #FF5733;
      color: white;
      position: relative;
    }
```
