### ISSUE TITLE
Car Game

### ISSUE THREAD

**Issue by mobeennn123** [jsfiddle/jsfiddle-issues#2103]
### Error code

ERRW:3518

### Were you logged in?

Yes

### Your username (if logged in)

mobeennn123

### Your HTML

```html
<div id="game-container">
        <div id="hud">
            <div class="hud-panel">Score: <span id="score-display">0</span></div>
            <div class="hud-panel"><div id="coin-icon"></div> <span id="coin-display">0</span></div>
            <div class="hud-panel"><div id="boost-icon"></div> <span id="boost-display">0</span></div>
        </div>
        
        <div id="boost-timer">BOOST: <span id="boost-time">10</span>s</div>
        
        <div id="start-screen">
            <div class="panel">
                <h1>HYPER CAR RUNNER</h1>
                <p>Collect coins to unlock new vehicles!</p>
                <p>Grab boosters for insane speed!</p>
                <p>Use arrow keys to move and space to nitro</p>
                <button id="start-button">START RACE</button>
                <button id="character-button">GARAGE</button>
            </div>
        </div>
        
        <div id="character-select" class="hidden">
            <div class="panel">
                <h1>GARAGE</h1>
                <p>Coins: <strong><span id="available-coins">0</span></strong></p>
                <div class="characters">
                    <!-- Characters will be added by JavaScript -->
                </div>
                <button id="back-button">BACK</button>
            </div>
        </div>
        
        <div id="game-over-screen" class="hidden">
            <div class="panel">
                <h1>RACE OVER!</h1>
                <p>You collected <strong><span id="final-coins">0</span></strong> coins!</p>
                <p>Total coins: <strong><span id="total-coins">0</span></strong></p>
                <button id="restart-button">RACE AGAIN</button>
                <button id="character-select-button">GARAGE</button>
            </div>
        </div>
        
        <canvas id="game-canvas"></canvas>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
```

### Your JavaScript

```javascript
// Game variables
let score = 0
let coinsCollected = 0
let totalCoins = 0
let boostsCollected = 0
let gameOver = false
let gameStarted = false
let isBoosting = false
let boostEndTime = 0
let lane = 0 // -1: left, 0: center, 1: right
let obstacles = []
let coins = []
let boosters = []
let brokenPixels = []
let selectedCharacter = 0

// Characters data - now as different car types
const characters = [
  {
    id: 0,
    name: 'Green Sedan',
    cost: 0,
    color: 0x00aa00,
    size: [1.2, 0.6, 2.0],
    speed: 1.0,
  },
  {
    id: 1,
    name: 'Red Sports',
    cost: 50,
    color: 0xff0000,
    size: [1.0, 0.5, 2.2],
    speed: 1.2,
  },
  {
    id: 2,
    name: 'Blue Truck',
    cost: 100,
    color: 0x0000ff,
    size: [1.5, 0.8, 2.5],
    speed: 0.8,
  },
  {
    id: 3,
    name: 'Lamborghini',
    cost: 500,
    color: 0xffa500,
    size: [1.1, 0.5, 2.3],
    speed: 1.5,
  },
  {
    id: 4,
    name: 'Black SUV',
    cost: 200,
    color: 0x111111,
    size: [1.4, 0.9, 2.4],
    speed: 0.9,
  },
  {
    id: 5,
    name: 'Rainbow Racer',
    cost: 1000,
    color: 0xffffff,
    size: [1.1, 0.5, 2.1],
    speed: 2.0,
  },
]

// Three.js variables
let scene, camera, renderer
let car, ground
let obstacleMeshes = []
let coinMeshes = []
let boosterMeshes = []
let pixelMeshes = []

// DOM elements
const scoreDisplay = document.getElementById('score-display')
const coinDisplay = document.getElementById('coin-display')
const boostDisplay = document.getElementById('boost-display')
const availableCoinsDisplay = document.getElementById('available-coins')
const finalCoinsDisplay = document.getElementById('final-coins')
const totalCoinsDisplay = document.getElementById('total-coins')
const boostTimer = document.getElementById('boost-timer')
const boostTimeDisplay = document.getElementById('boost-time')
const startScreen = document.getElementById('start-screen')
const gameOverScreen = document.getElementById('game-over-screen')
const characterSelectScreen = document.getElementById('character-select')
const charactersContainer = document.querySelector('.characters')
const startButton = document.getElementById('start-button')
const characterButton = document.getElementById('character-button')
const backButton = document.getElementById('back-button')
const restartButton = document.getElementById('restart-button')
const characterSelectButton = document.getElementById('character-select-button')
const canvas = document.getElementById('game-canvas')

// Create a car model with more details
function createCar(color, isLambo = false) {
  const carGroup = new THREE.Group()

  // Car body (main part)
  const bodyGeometry = isLambo
    ? new THREE.BoxGeometry(1.1, 0.4, 2.3)
    : new THREE.BoxGeometry(1.2, 0.4, 2.0)
  const bodyMaterial = new THREE.MeshStandardMaterial({ color })
  const body = new THREE.Mesh(bodyGeometry, bodyMaterial)
  carGroup.add(body)

  // Car roof
  const roofGeometry = isLambo
    ? new THREE.BoxGeometry(0.9, 0.2, 1.0)
    : new THREE.BoxGeometry(0.8, 0.2, 1.2)
  const roof = new THREE.Mesh(roofGeometry, bodyMaterial)
  roof.position.y = 0.3
  carGroup.add(roof)

  // Windows
  const windowMaterial = new THREE.MeshStandardMaterial({
    color: 0x333333,
    transparent: true,
    opacity: 0.7,
  })

  const frontWindowGeometry = isLambo
    ? new THREE.BoxGeometry(0.9, 0.2, 0.4)
    : new THREE.BoxGeometry(0.8, 0.2, 0.5)
  const frontWindow = new THREE.Mesh(frontWindowGeometry, windowMaterial)
  frontWindow.position.set(0, 0.3, isLambo ? 0.5 : 0.4)
  carGroup.add(frontWindow)

  const backWindowGeometry = isLambo
    ? new THREE.BoxGeometry(0.9, 0.2, 0.4)
    : new THREE.BoxGeometry(0.8, 0.2, 0.5)
  const backWindow = new THREE.Mesh(backWindowGeometry, windowMaterial)
  backWindow.position.set(0, 0.3, isLambo ? -0.5 : -0.4)
  carGroup.add(backWindow)

  // Wheels
  const wheelGeometry = new THREE.CylinderGeometry(0.2, 0.2, 0.1, 16)
  const wheelMaterial = new THREE.MeshStandardMaterial({ color: 0x222222 })

  // Special wheels for Lamborghini
  if (isLambo) {
    const lamboWheelGeometry = new THREE.CylinderGeometry(0.2, 0.2, 0.15, 32)
    const lamboWheelMaterial = new THREE.MeshStandardMaterial({
      color: 0x111111,
      roughness: 0.3,
      metalness: 0.9,
    })

    const lamboWheelPositions = [
      { x: 0.6, y: -0.3, z: 0.7 },
      { x: -0.6, y: -0.3, z: 0.7 },
      { x: 0.6, y: -0.3, z: -0.7 },
      { x: -0.6, y: -0.3, z: -0.7 },
    ]

    lamboWheelPositions.forEach((pos) => {
      const wheel = new THREE.Mesh(lamboWheelGeometry, lamboWheelMaterial)
      wheel.rotation.z = Math.PI / 2
      wheel.position.set(pos.x, pos.y, pos.z)
      carGroup.add(wheel)
    })

    // Add Lamborghini details
    const detailsGeometry = new THREE.BoxGeometry(0.05, 0.05, 0.3)
    const detailsMaterial = new THREE.MeshStandardMaterial({ color: 0x000000 })

    // Side vents
    const leftVent = new THREE.Mesh(detailsGeometry, detailsMaterial)
    leftVent.position.set(0.55, 0.1, 0)
    carGroup.add(leftVent)

    const rightVent = new THREE.Mesh(detailsGeometry, detailsMaterial)
    rightVent.position.set(-0.55, 0.1, 0)
    carGroup.add(rightVent)

    // Spoiler
    const spoilerGeometry = new THREE.BoxGeometry(1.3, 0.05, 0.1)
    const spoiler = new THREE.Mesh(spoilerGeometry, detailsMaterial)
    spoiler.position.set(0, 0.4, -0.9)
    carGroup.add(spoiler)
  } else {
    const wheelPositions = [
      { x: 0.5, y: -0.3, z: 0.6 },
      { x: -0.5, y: -0.3, z: 0.6 },
      { x: 0.5, y: -0.3, z: -0.6 },
      { x: -0.5, y: -0.3, z: -0.6 },
    ]

    wheelPositions.forEach((pos) => {
      const wheel = new THREE.Mesh(wheelGeometry, wheelMaterial)
      wheel.rotation.z = Math.PI / 2
      wheel.position.set(pos.x, pos.y, pos.z)
      carGroup.add(wheel)
    })
  }

  return carGroup
}

// Create a booster item
function createBooster() {
  const group = new THREE.Group()

  // Base
  const baseGeometry = new THREE.CylinderGeometry(0.4, 0.4, 0.2, 32)
  const baseMaterial = new THREE.MeshStandardMaterial({
    color: 0xff0000,
    emissive: 0x880000,
    emissiveIntensity: 0.5,
  })
  const base = new THREE.Mesh(baseGeometry, baseMaterial)
  group.add(base)

  // Flame core
  const coreGeometry = new THREE.SphereGeometry(0.3, 16, 16)
  const coreMaterial = new THREE.MeshStandardMaterial({
    color: 0xff8800,
    emissive: 0xff3300,
    emissiveIntensity: 0.8,
  })
  const core = new THREE.Mesh(coreGeometry, coreMaterial)
  core.position.y = 0.1
  group.add(core)

  return group
}

// Create broken pixel effect
function createBrokenPixel(position) {
  const size = 0.2 + Math.random() * 0.3
  const geometry = new THREE.BoxGeometry(size, size, size)
  const colors = [0xff0000, 0x00ff00, 0x0000ff, 0xffff00, 0xff00ff, 0x00ffff]
  const material = new THREE.MeshStandardMaterial({
    color: colors[Math.floor(Math.random() * colors.length)],
    emissive: 0x333333,
    emissiveIntensity: 0.5,
  })
  const pixel = new THREE.Mesh(geometry, material)
  pixel.position.copy(position)
  pixel.rotation.set(
    Math.random() * Math.PI,
    Math.random() * Math.PI,
    Math.random() * Math.PI,
  )

  // Add physics-like properties
  pixel.userData = {
    velocity: new THREE.Vector3(
      (Math.random() - 0.5) * 0.2,
      Math.random() * 0.3,
      (Math.random() - 0.5) * 0.2,
    ),
    rotationSpeed: new THREE.Vector3(
      Math.random() * 0.1,
      Math.random() * 0.1,
      Math.random() * 0.1,
    ),
    gravity: -0.01,
    lifetime: 100 + Math.random() * 50,
  }

  scene.add(pixel)
  brokenPixels.push(pixel)
  return pixel
}

// Initialize the game
function init() {
  // Load saved coins and character
  const savedData = localStorage.getItem('hyperCarRunnerData')
  if (savedData) {
    const data = JSON.parse(savedData)
    totalCoins = data.totalCoins || 0
    selectedCharacter = data.selectedCharacter || 0
  }

  // Set up Three.js scene
  scene = new THREE.Scene()
  scene.background = new THREE.Color(0x111122)
  camera = new THREE.PerspectiveCamera(
    75,
    window.innerWidth / window.innerHeight,
    0.1,
    1000,
  )
  renderer = new THREE.WebGLRenderer({ canvas, antialias: true })
  renderer.setSize(window.innerWidth, window.innerHeight)

  // Set up camera
  camera.position.set(0, 5, 10)
  camera.lookAt(0, 0, 0)

  // Add lights
  const ambientLight = new THREE.AmbientLight(0x404040)
  scene.add(ambientLight)

  const directionalLight = new THREE.DirectionalLight(0xffffff, 0.8)
  directionalLight.position.set(1, 1, 1)
  scene.add(directionalLight)

  // Add some city-like background elements
  for (let i = 0; i < 20; i++) {
    const building = new THREE.Mesh(
      new THREE.BoxGeometry(
        2 + Math.random() * 5,
        5 + Math.random() * 20,
        2 + Math.random() * 5,
      ),
      new THREE.MeshStandardMaterial({
        color: 0x333344,
        emissive: 0x111122,
        emissiveIntensity: 0.2,
      }),
    )
    building.position.set(
      (Math.random() - 0.5) * 100,
      0,
      -50 - Math.random() * 100,
    )
    scene.add(building)
  }

  // Create car (player)
  createPlayerCar()

  // Create road
  const roadGeometry = new THREE.PlaneGeometry(20, 100)
  const roadMaterial = new THREE.MeshStandardMaterial({
    color: 0x222233,
    roughness: 0.9,
    metalness: 0.1,
  })
  ground = new THREE.Mesh(roadGeometry, roadMaterial)
  ground.rotation.x = -Math.PI / 2
  ground.position.y = -1
  scene.add(ground)

  // Add lane markers
  for (let i = -1; i <= 1; i++) {
    const markerGeometry = new THREE.BoxGeometry(0.1, 0.05, 100)
    const markerMaterial = new THREE.MeshStandardMaterial({
      color: 0xffffff,
      emissive: 0x8888ff,
      emissiveIntensity: 0.3,
    })
    const marker = new THREE.Mesh(markerGeometry, markerMaterial)
    marker.position.set(i * 3, -0.9, 0)
    scene.add(marker)
  }

  // Populate character selection
  renderCharacterSelection()

  // Event listeners
  startButton.addEventListener('click', startGame)
  characterButton.addEventListener('click', showCharacterSelect)
  backButton.addEventListener('click', hideCharacterSelect)
  restartButton.addEventListener('click', resetGame)
  characterSelectButton.addEventListener('click', showCharacterSelect)
  window.addEventListener('keydown', handleKeyDown)
  window.addEventListener('keyup', handleKeyUp)
  window.addEventListener('resize', onWindowResize)

  // Start animation loop
  animate()
}

// Create player car based on selected character
function createPlayerCar() {
  if (car) scene.remove(car)

  const char = characters[selectedCharacter]
  const isLambo = char.id === 3
  car = createCar(char.color, isLambo)

  // Scale based on character size
  car.scale.set(
    char.size[0] / (isLambo ? 1.1 : 1.2),
    char.size[1] / 0.6,
    char.size[2] / (isLambo ? 2.3 : 2.0),
  )

  car.position.y = char.size[1] / 2
  scene.add(car)
}

// Render character selection screen
function renderCharacterSelection() {
  charactersContainer.innerHTML = ''

  characters.forEach((char) => {
    const charElement = document.createElement('div')
    charElement.className = `character ${char.id === selectedCharacter ? 'selected' : ''} ${char.cost > totalCoins && char.id !== selectedCharacter ? 'locked' : ''}`

    // Create a mini car preview
    const previewCanvas = document.createElement('canvas')
    previewCanvas.width = 80
    previewCanvas.height = 80
    const ctx = previewCanvas.getContext('2d')

    // Draw simple car shape with character color
    ctx.fillStyle = `#${char.color.toString(16).padStart(6, '0')}`

    // Different shapes for different cars
    if (char.id === 3) {
      // Lamborghini
      ctx.fillRect(20, 40, 60, 20) // body
      ctx.fillRect(25, 30, 50, 10) // roof
      ctx.fillStyle = '#333333'
      ctx.fillRect(35, 33, 30, 5) // window
      // Wheels
      ctx.fillStyle = '#111111'
      ctx.beginPath()
      ctx.arc(30, 60, 8, 0, Math.PI * 2)
      ctx.fill()
      ctx.beginPath()
      ctx.arc(70, 60, 8, 0, Math.PI * 2)
      ctx.fill()
    } else if (char.id === 5) {
      // Rainbow racer
      const gradient = ctx.createLinearGradient(0, 0, 80, 0)
      gradient.addColorStop(0, 'red')
      gradient.addColorStop(0.2, 'orange')
      gradient.addColorStop(0.4, 'yellow')
      gradient.addColorStop(0.6, 'green')
      gradient.addColorStop(0.8, 'blue')
      gradient.addColorStop(1, 'purple')
      ctx.fillStyle = gradient
      ctx.fillRect(15, 40, 50, 20)
      ctx.fillRect(20, 30, 40, 10)
    } else {
      ctx.fillRect(15, 40, 50, 20) // body
      ctx.fillRect(20, 30, 40, 10) // roof
      ctx.fillStyle = '#333333'
      ctx.fillRect(30, 33, 20, 5) // window
    }

    charElement.appendChild(previewCanvas)

    // Add name
    const nameElement = document.createElement('div')
    nameElement.className = 'character-name'
    nameElement.textContent = char.name
    charElement.appendChild(nameElement)

    if (char.cost > 0) {
      const costElement = document.createElement('div')
      costElement.className = 'character-cost'
      costElement.textContent = char.cost
      charElement.appendChild(costElement)
    }

    if (char.cost <= totalCoins || char.id === selectedCharacter) {
      charElement.addEventListener('click', () => selectCharacter(char.id))
    }

    charactersContainer.appendChild(charElement)
  })

  availableCoinsDisplay.textContent = totalCoins
}

// Select character
function selectCharacter(id) {
  if (characters[id].cost > totalCoins && id !== selectedCharacter) return

  selectedCharacter = id
  createPlayerCar()
  renderCharacterSelection()

  // Save selection
  saveGameData()
}

// Save game data to localStorage
function saveGameData() {
  localStorage.setItem(
    'hyperCarRunnerData',
    JSON.stringify({
      totalCoins,
      selectedCharacter,
    }),
  )
}

// Animation loop
function animate() {
  requestAnimationFrame(animate)

  if (!gameStarted || gameOver) {
    return
  }

  // Update boost timer
  if (isBoosting) {
    const timeLeft = Math.max(0, boostEndTime - Date.now())
    const secondsLeft = Math.ceil(timeLeft / 1000)
    boostTimeDisplay.textContent = secondsLeft

    if (timeLeft <= 0) {
      isBoosting = false
      boostTimer.style.display = 'none'
    }
  }

  // Update car position (lane and boost)
  car.position.x = lane * 3

  // Boost effect
  if (isBoosting) {
    car.position.y =
      characters[selectedCharacter].size[1] / 2 +
      Math.sin(Date.now() * 0.02) * 0.1
    car.rotation.z = Math.sin(Date.now() * 0.05) * 0.1

    // Add boost particles
    if (Math.random() < 0.3) {
      const exhaustPos = new THREE.Vector3(
        car.position.x,
        car.position.y - 0.3,
        car.position.z - 1,
      )
      createBrokenPixel(exhaustPos)
    }
  } else {
    car.position.y = characters[selectedCharacter].size[1] / 2
    car.rotation.z = 0
  }

  // Rotate wheels
  const rotationSpeed = isBoosting ? 0.3 : 0.1
  car.children.forEach((child) => {
    if (child.geometry && child.geometry.type === 'CylinderGeometry') {
      child.rotation.x += rotationSpeed
    }
  })

  // Update broken pixels
  brokenPixels.forEach((pixel, index) => {
    pixel.userData.lifetime--
    if (pixel.userData.lifetime <= 0) {
      scene.remove(pixel)
      brokenPixels.splice(index, 1)
      return
    }

    pixel.position.add(pixel.userData.velocity)
    pixel.rotation.x += pixel.userData.rotationSpeed.x
    pixel.rotation.y += pixel.userData.rotationSpeed.y
    pixel.rotation.z += pixel.userData.rotationSpeed.z
    pixel.userData.velocity.y += pixel.userData.gravity
    pixel.material.opacity = pixel.userData.lifetime / 150
  })

  // Generate obstacles, coins and boosters randomly
  const baseSpeed = characters[selectedCharacter].speed
  const speedMultiplier = isBoosting ? 10 : 1
  const currentSpeed = baseSpeed * speedMultiplier

  if (Math.random() < 0.02) {
    const obstacleLane = Math.floor(Math.random() * 3) - 1 // -1, 0, or 1
    const obstacle = {
      x: obstacleLane * 3,
      y: 0.5,
      z: -20,
      mesh: null,
    }

    // Create obstacle as a traffic cone or car
    let obstacleMesh
    if (Math.random() > 0.5) {
      // Traffic cone
      const coneGeometry = new THREE.ConeGeometry(0.5, 1, 16)
      const coneMaterial = new THREE.MeshStandardMaterial({
        color: 0xff6600,
        emissive: 0x884400,
        emissiveIntensity: 0.2,
      })
      obstacleMesh = new THREE.Mesh(coneGeometry, coneMaterial)
      obstacleMesh.rotation.x = Math.PI / 2
    } else {
      // Other car
      const carColor = Math.random() > 0.5 ? 0x888888 : 0xcccccc
      obstacleMesh = createCar(carColor)
      obstacleMesh.scale.set(0.8, 0.8, 0.8)
    }

    obstacleMesh.position.set(obstacle.x, obstacle.y, obstacle.z)
    scene.add(obstacleMesh)
    obstacle.mesh = obstacleMesh
    obstacles.push(obstacle)
  }

  if (Math.random() < 0.05) {
    const coinLane = Math.floor(Math.random() * 3) - 1
    const coin = {
      x: coinLane * 3,
      y: 0.5,
      z: -20,
      mesh: null,
    }

    // Create coin
    const coinGeometry = new THREE.CylinderGeometry(0.5, 0.5, 0.1, 32)
    const coinMaterial = new THREE.MeshStandardMaterial({
      color: 0xffd700,
      roughness: 0.3,
      metalness: 0.7,
      emissive: 0xaa8800,
      emissiveIntensity: 0.3,
    })

    const coinMesh = new THREE.Mesh(coinGeometry, coinMaterial)
    coinMesh.position.set(coin.x, coin.y, coin.z)
    scene.add(coinMesh)

    coins.push(coin)
    coin.mesh = coinMesh
  }

  if (Math.random() < 0.01 && !isBoosting) {
    const boosterLane = Math.floor(Math.random() * 3) - 1
    const booster = {
      x: boosterLane * 3,
      y: 0.5,
      z: -20,
      mesh: null,
    }

    // Create booster
    const boosterMesh = createBooster()
    boosterMesh.position.set(booster.x, booster.y, booster.z)
    scene.add(boosterMesh)

    boosters.push(booster)
    booster.mesh = boosterMesh
  }

  // Move obstacles, coins and boosters towards player
  obstacles.forEach((obstacle, index) => {
    obstacle.z += 0.2 * currentSpeed
    obstacle.mesh.position.z = obstacle.z

    // Remove if past player
    if (obstacle.z > 5) {
      scene.remove(obstacle.mesh)
      obstacles.splice(index, 1)
    }

    // Check collision
    const charWidth = characters[selectedCharacter].size[0]
    if (
      Math.abs(obstacle.z) < 1 &&
      Math.abs(obstacle.x - lane * 3) < charWidth / 2 + 0.75
    ) {
      // Create broken pixels on collision
      for (let i = 0; i < 20; i++) {
        createBrokenPixel(car.position.clone())
      }

      gameOver = true
      totalCoins += coinsCollected
      saveGameData()

      finalCoinsDisplay.textContent = coinsCollected
      totalCoinsDisplay.textContent = totalCoins
      gameOverScreen.classList.remove('hidden')
    }
  })

  coins.forEach((coin, index) => {
    coin.z += 0.2 * currentSpeed
    coin.mesh.position.z = coin.z
    coin.mesh.rotation.y += 0.1

    // Remove if past player
    if (coin.z > 5) {
      scene.remove(coin.mesh)
      coins.splice(index, 1)
    }

    // Check collision
    if (Math.abs(coin.z) < 1 && Math.abs(coin.x - lane * 3) < 1.5) {
      coinsCollected++
      score += 10
      coinDisplay.textContent = coinsCollected
      scene.remove(coin.mesh)
      coins.splice(index, 1)

      // Create sparkle effect
      for (let i = 0; i < 5; i++) {
        createBrokenPixel(coin.mesh.position.clone())
      }
    }
  })

  boosters.forEach((booster, index) => {
    booster.z += 0.2 * currentSpeed
    booster.mesh.position.z = booster.z
    booster.mesh.rotation.y += 0.05

    // Pulsing effect
    booster.mesh.scale.setScalar(1 + Math.sin(Date.now() * 0.01) * 0.1)

    // Remove if past player
    if (booster.z > 5) {
      scene.remove(booster.mesh)
      boosters.splice(index, 1)
    }

    // Check collision
    if (Math.abs(booster.z) < 1 && Math.abs(booster.x - lane * 3) < 1.5) {
      // Activate boost
      isBoosting = true
      boostEndTime = Date.now() + 10000 // 10 seconds
      boostTimer.style.display = 'block'
      boostsCollected++
      boostDisplay.textContent = boostsCollected

      // Create explosion effect
      for (let i = 0; i < 30; i++) {
        createBrokenPixel(booster.mesh.position.clone())
      }

      scene.remove(booster.mesh)
      boosters.splice(index, 1)
    }
  })

  // Increment score over time
  score += 0.1 * currentSpeed
  scoreDisplay.textContent = Math.floor(score)

  renderer.render(scene, camera)
}

// Handle keyboard controls
function handleKeyDown(e) {
  if (!gameStarted || gameOver) return

  if (e.code === 'Space') {
    // Nitro boost when space is pressed
    if (!isBoosting && boostsCollected > 0) {
      isBoosting = true
      boostEndTime = Date.now() + 10000 // 10 seconds
      boostsCollected--
      boostDisplay.textContent = boostsCollected
      boostTimer.style.display = 'block'
    }
  }
  if (e.key === 'ArrowLeft') {
    lane = Math.max(-1, lane - 1)
  }
  if (e.key === 'ArrowRight') {
    lane = Math.min(1, lane + 1)
  }
}

// Handle key release for boost
function handleKeyUp(e) {
  if (e.code === 'Space') {
    // Don't release boost - it's timed
  }
}

// Start the game
function startGame() {
  gameStarted = true
  startScreen.classList.add('hidden')
}

// Show character select
function showCharacterSelect() {
  characterSelectScreen.classList.remove('hidden')
  if (gameStarted && !gameOver) {
    gameStarted = false
  }
}

// Hide character select
function hideCharacterSelect() {
  characterSelectScreen.classList.add('hidden')
  if (!gameOver) {
    gameStarted = true
  }
}

// Reset the game
function resetGame() {
  // Reset game state
  score = 0
  coinsCollected = 0
  boostsCollected = 0
  gameOver = false
  gameStarted = true
  isBoosting = false

  // Clear all objects
  obstacles.forEach((obstacle) => scene.remove(obstacle.mesh))
  coins.forEach((coin) => scene.remove(coin.mesh))
  boosters.forEach((booster) => scene.remove(booster.mesh))
  brokenPixels.forEach((pixel) => scene.remove(pixel))
  obstacles = []
  coins = []
  boosters = []
  brokenPixels = []

  // Reset car position
  const char = characters[selectedCharacter]
  car.position.set(0, char.size[1] / 2, 0)
  car.rotation.set(0, 0, 0)
  lane = 0

  // Update UI
  scoreDisplay.textContent = '0'
  coinDisplay.textContent = '0'
  boostDisplay.textContent = '0'
  boostTimer.style.display = 'none'
  gameOverScreen.classList.add('hidden')
}

// Handle window resize
function onWindowResize() {
  camera.aspect = window.innerWidth / window.innerHeight
  camera.updateProjectionMatrix()
  renderer.setSize(window.innerWidth, window.innerHeight)
}

// Start the game
init()
```

### Your CSS

```css
body { 
            margin: 0;
            overflow: hidden;
            font-family: Arial, sans-serif;
            background: #000;
        }
        #game-container {
            position: relative;
            width: 100vw;
            height: 100vh;
        }
        #hud {
            position: absolute;
            top: 20px;
            left: 20px;
            z-index: 10;
            display: flex;
            gap: 20px;
        }
        .hud-panel {
            background: rgba(0, 0, 0, 0.7);
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            font-size: 24px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        #coin-icon {
            width: 24px;
            height: 24px;
            background: radial-gradient(circle, gold 40%, darkgoldenrod 100%);
            border-radius: 50%;
            border: 2px solid goldenrod;
        }
        #boost-icon {
            width: 24px;
            height: 24px;
            background: radial-gradient(circle, #ff0000 40%, #880000 100%);
            border-radius: 50%;
            border: 2px solid #ff3333;
        }
        #start-screen, #game-over-screen, #character-select {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            background: rgba(0, 0, 0, 0.7);
            z-index: 20;
        }
        .panel {
            background: #111;
            color: white;
            padding: 30px;
            border-radius: 10px;
            text-align: center;
            max-width: 500px;
            width: 80%;
            border: 2px solid #333;
        }
        .panel h1 {
            margin-top: 0;
            color: #4CAF50;
        }
        button {
            background: #4CAF50;
            color: white;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 20px;
            transition: all 0.2s;
        }
        button:hover {
            background: #45a049;
            transform: scale(1.05);
        }
        button:disabled {
            background: #333;
            cursor: not-allowed;
            color: #666;
        }
        .hidden {
            display: none !important;
        }
        .characters {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            gap: 15px;
            margin-top: 20px;
        }
        .character {
            width: 100px;
            height: 100px;
            border: 3px solid #333;
            border-radius: 5px;
            display: flex;
            justify-content: center;
            align-items: center;
            cursor: pointer;
            transition: all 0.2s;
            background: #222;
            position: relative;
        }
        .character:hover {
            border-color: #4CAF50;
            transform: scale(1.05);
        }
        .character.selected {
            border-color: #4CAF50;
            background-color: rgba(76, 175, 80, 0.2);
            box-shadow: 0 0 15px #4CAF50;
        }
        .character.locked {
            position: relative;
            filter: grayscale(100%);
        }
        .character.locked::after {
            content: "🔒";
            position: absolute;
            top: -10px;
            right: -10px;
            font-size: 20px;
        }
        .character-cost {
            position: absolute;
            bottom: 5px;
            right: 5px;
            background: gold;
            color: black;
            border-radius: 50%;
            width: 20px;
            height: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 12px;
            font-weight: bold;
        }
        .character-name {
            position: absolute;
            bottom: -20px;
            width: 100%;
            text-align: center;
            font-size: 12px;
            color: white;
        }
        #boost-timer {
            position: absolute;
            top: 20px;
            right: 20px;
            background: rgba(0, 0, 0, 0.7);
            color: red;
            padding: 10px 20px;
            border-radius: 5px;
            font-size: 24px;
            display: none;
        }
```
