### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by SNHliulangmiao** [jsfiddle/jsfiddle-issues#2106]
### Error code

ERRW:1.0:K1.0:AS

### Were you logged in?

Yes

### Your username (if logged in)

liulangmaio

### Your HTML

```html
<header>
        <h1>L'ús de IA & DeepFake</h1>
    </header>

    <button class="btn-mode" onclick="toggleDarkMode()">Canvia Mode Clar/Oscur</button>

    <nav>
        <a href="#ia">L'ús de IA</a>
        <a href="#deepfake">DeepFake</a>
        <a href="#joc">Joc</a>
    </nav>

    <section id="ia">
        <h2>L'ús de la Intel·ligència Artificial (IA)</h2>

        <details>
            <summary>1. Què és</summary>
            <p>La intel·ligència artificial és una disciplina que combina diferents capacitats mentals com el raonament i l’aprenentatge, però aplicades a sistemes informàtics. Fa servir les matemàtiques i la lògica per imitar el pensament humà.</p>
        </details>

        <details>
            <summary>2. Tipus de IA</summary>
            <p>Per capaciat:</p>
            <ul>
                <li><strong>La intel·ligència artificial estreta (narrow AI):</strong> Dissenyada per fer tasques específiques i no pot sortir-se’n bé si intenta fer coses per les quals no està programada.</li>
                <li><strong>La intel·ligència artificial general (General AI):</strong> imitar el pensament humà i actuar amb autonomia</li>
                <li><strong>La Super IA (ASI):</strong> Seria una intel·ligència artificial capaç de superar els humans en qualsevol activitat, incloent-hi pensar, raonar, resoldre problemes, prendre decisions pròpies, aprendre de l'experiència i comunicar-se de manera autònoma.</li>
            </ul>
          <p>Per funcionalitat:</p>
            <ul>
                <li><strong>Màquines reactives:</strong> No recorden experiències passades ni aprenen d'elles, simplement responen al moment present amb la informació que tenen en aquell instant.</li>
                <li><strong>Memòria Limitada::</strong> pot recordar informació durant un temps curt per millorar el seu rendiment.</li>
                <li><strong>IA de Teoria de la Ment:</strong> podria entendre emocions, creences i normes socials per interactuar amb les persones de manera similar a com ho fem entre nosaltres.</li>
              <li><strong>Màquines Autoconscients:</strong> Recorda experiències passades i també forma el seu propi criteri i pren decisions segons el que consideri adequat.</li>
            </ul>
        </details>

        <details>
            <summary>3. Camps d'aplicació</summary>
            <p>La IA s'aplica en àmbits com:</p>
            <ul>
                <li>Salut: diagnòstic mèdic, anàlisi d'imatges.</li>
                <li>Educació: tutors intel·ligents, personalització de l'aprenentatge.</li>
                <li>Automoció: cotxes autònoms.</li>
                <li>Negocis: anàlisi predictiva, automatització de processos.</li>
              <li>Advocacia i justícia: pot ajudar facilitant la recerca de dades, estalviant temps i millorant l’eficiència. També pot afavorir la transparència i l’equitat en els judicis mitjançant l’anàlisi de gravacions per evitar errors o corrupció.</li>
              <li>Vida quotidiana i servei: dissenyats per assistir persones en diverses tasques, diferenciant-se dels robots industrials pel seu àmbit d'aplicació, per exemple robots de neteja.</li>
              <li>Agricultura: per optimitzar la gestió agrícola. Això permet als agricultors monitoritzar i analitzar en temps real aspectes com la meteorologia, la hidrologia o l’estat dels cultius, millorant així la presa de decisions.</li>
            </ul>
        </details>

        <details>
            <summary>4. Riscs i problemes</summary>
            <p>Tot i els seus beneficis, la IA també comporta riscos:</p>
            <ul>
                <li>Desinformació i manipulació.</li>
                <li>Pèrdua de llocs de treball per automatització.</li>
                <li>Biaixos en dades i algoritmes.</li>
                <li>Riscos ètics i de privacitat.</li>
            </ul>
        </details>
    </section>

    <section id="deepfake">
        <h2>DeepFake</h2>
        <p>Actualment no obert.</p>
    </section>

    <section id="joc">
        <h2>Joc</h2>
        <p>Actualment no obert.</p>
    </section>

    <footer>
        <p>&copy; 2025 L'ús de IA & DeepFake</p>
    </footer>
```

### Your JavaScript

```javascript
function toggleDarkMode() {
            const body = document.body;
            body.classList.toggle("dark-mode");
            if (body.classList.contains("dark-mode")) {
                body.style.backgroundColor = "#121212";
                document.querySelectorAll("section").forEach(s => s.style.backgroundColor = "#1e1e1e");
                document.querySelectorAll("section").forEach(s => s.style.color = "#f0f0f0");
            } else {
                body.style.backgroundColor = "#f5f5f5";
                document.querySelectorAll("section").forEach(s => s.style.backgroundColor = "white");
                document.querySelectorAll("section").forEach(s => s.style.color = "black");
            }
        }
```

### Your CSS

```css
body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
            transition: background-color 0.3s;
        }
        header {
            background-color: #333;
            color: white;
            padding: 1.5em 1em;
            text-align: center;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
        }
        nav {
            background-color: #444;
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
        }
        nav a {
            color: white;
            padding: 1em;
            text-decoration: none;
            transition: background-color 0.3s;
        }
        nav a:hover {
            background-color: #666;
        }
        section {
            padding: 2em;
            background-color: white;
            margin: 1em;
            border-radius: 12px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s;
        }
        section:hover {
            transform: scale(1.02);
        }
        footer {
            text-align: center;
            padding: 1em;
            background-color: #333;
            color: white;
            margin-top: 2em;
        }
        iframe {
            border: none;
            width: 100%;
            height: 400px;
            border-radius: 8px;
        }
        .btn-mode {
            background-color: #007BFF;
            color: white;
            border: none;
            padding: 0.6em 1.2em;
            border-radius: 8px;
            cursor: pointer;
            margin: 1em auto;
            display: block;
            transition: background-color 0.3s;
        }
        .btn-mode:hover {
            background-color: #0056b3;
        }
        details {
            margin-bottom: 1em;
            background: #f0f0f0;
            padding: 1em;
            border-radius: 8px;
            transition: background 0.3s;
        }
        summary {
            cursor: pointer;
            font-weight: bold;
            font-size: 1.1em;
        }
        @media (max-width: 768px) {
            nav a {
                flex: 1 1 100%;
                text-align: center;
            }
            section {
                margin: 1em 0.5em;
            }
        }
```
