### ISSUE TITLE
🤖 Cannot save fiddle

### ISSUE THREAD

**Issue by CarbonFormula** [jsfiddle/jsfiddle-issues#2111]
### Error code

ERRW:1.0:K1.0:PRMS0.7

### Were you logged in?

Yes

### Your username (if logged in)

CarbonFormula

### Your HTML

```html
<!-- Home Screen -->
  <div id="home-screen" class="screen">
    <h1 class="title">Desert Racer 2.0</h1>
    <div class="button-container">
      <button id="shop-btn" class="game-btn">🛒 Shop</button>
      <button id="play-btn" class="game-btn">▶️ Play</button>
      <button id="credits-btn" class="game-btn">🍿 Credits</button>
    </div>
  </div>

  <!-- Settings Modal -->
  <div id="settingsModal">
    <button class="close-btn" id="closeSettingsBtn">X</button>
    <h2>Adjust Turn Speed</h2>
    <input type="range" id="turnSpeedSlider" min="1" max="10" value="5">
    <p id="turnSpeedValue">Turn Speed: 5</p>
    <button id="applySettingsBtn">Apply & Resume</button>
  </div>

  <!-- Shop Screen -->
  <div id="shop-screen" class="screen">
    <div class="back-btn-container">
      <button id="back-btn-shop" class="back-btn">Back</button>
    </div>
    <div class="shop-content">
      <h2>Shop</h2>
      <p>Here you can buy cars with the coins you collect in the game!</p>
    </div>
  </div>

  <!-- Credits Screen -->
  <div id="credits-screen" class="screen">
    <div class="back-btn-container">
      <button id="back-btn-credits" class="back-btn">Back</button>
    </div>
    <div class="credits-content">
      <h2>Game Instructions</h2>
      <p>1. Collect coins while avoiding obstacles!</p>
      <p>2. Hit a cactus to retry, or hit an oil spill to spin out!</p>
      <p>3. Use the power-boosts to speed through obstacles!</p>
    </div>
  </div>

  <!-- Game Canvas -->
  <div id="powerUpBarContainer">
    <div id="powerUpBar"></div>
  </div>
  <div id="overlay">
    <div>Whoops! You hit a cactus!</div>
    <div>
      <button id="playAgainBtn">Play Again</button>
      <button id="goToShopBtn">Go To Shop</button>
    </div>
  </div>
  <div id="shopScreen">
    <h1>Car Shop</h1>
    <div id="carList" style="display:flex; flex-wrap: wrap; justify-content:center;"></div>
    <button id="closeShopBtn" style="margin-top: 20px;">Close Shop</button>
  </div>
  <div id="hud">
    <span>Speed: <span id="speedDisplay">0</span> MPH</span>
    <span>Score: <span id="scoreDisplay">0</span></span>
    <span>Coins: <span id="coinsDisplay">0</span></span>
  </div>
  <div id="statsBox">
    <span id="statsSpeed">Speed: 0 MPH</span>
    <span id="statsScore">Score: 0</span>
    <span id="statsCoins">Coins: 0</span>
  </div>
  <canvas id="game" width="1000" height="800"></canvas>

  <button class="gear-btn" id="settingsBtn">⚙️</button>
```

### Your JavaScript

```javascript
(() => {
  const canvas = document.getElementById("game");
  const ctx = canvas.getContext("2d");

  // DOM elements
  const overlay = document.getElementById("overlay");
  const playAgainBtn = document.getElementById("playAgainBtn");
  const goToShopBtn = document.getElementById("goToShopBtn");
  const shopScreen = document.getElementById("shopScreen");
  const closeShopBtn = document.getElementById("closeShopBtn");
  const carListDiv = document.getElementById("carList");
  const powerUpBarContainer = document.getElementById("powerUpBarContainer");
  const powerUpBar = document.getElementById("powerUpBar");
  const speedDisplay = document.getElementById("speedDisplay");
  const scoreDisplay = document.getElementById("scoreDisplay");
  const coinsDisplay = document.getElementById("coinsDisplay");
  const settingsBtn = document.getElementById("settingsBtn");
  const settingsModal = document.getElementById("settingsModal");
  const closeSettingsBtn = document.getElementById("closeSettingsBtn");
  const turnSpeedSlider = document.getElementById("turnSpeedSlider");
  const turnSpeedValue = document.getElementById("turnSpeedValue");
  const applySettingsBtn = document.getElementById("applySettingsBtn");
  const statsBox = document.getElementById("statsBox");

  // Road config
  const roadWidth = 700; // Wider road
  const roadLeftEdge = (canvas.width - roadWidth) / 2;
  const roadRightEdge = roadLeftEdge + roadWidth;
  const laneMarkWidth = 6;

  // Car config
  const car = {
    x: canvas.width / 2,
    y: canvas.height - 180,
    width: 40,
    height: 90,
    speed: 2,
    maxSpeed: 10,
    speedIncreaseRate: 0.001,
    flyingSpeed: 25,
    rotation: 0,
    rotationSpeed: 0.1,
    isSpinning: false,
    spinDuration: 1000,
    spinTimer: 0,
    turnSpeed: 5, // Initial turn speed
    minSpeed: 2 // Set initial forward speed limit
  };

  // Game variables
  let score = 0;
  let coins = 0;
  let gameOver = false;
  let powerUpActive = false;
  let powerUpDuration = 5000;
  let powerUpTimeLeft = 0;
  let paused = false;

  // Controls
  const keys = {};
  window.addEventListener("keydown", e => {
    keys[e.key] = true;
    if (e.key === "p" || e.key === "P") {
      togglePause();
    }
  });
  window.addEventListener("keyup", e => keys[e.key] = false);

  // Car designs with details
  const carDesigns = [
    {
      id: 1,
      name: "Red Racer",
      price: 10, // Lower price
      owned: true,
      baseColor: "#cc0000",
      stripeColor: "#ffffff"
    },
    {
      id: 2,
      name: "Blue Blaze",
      price: 20, // Lower price
      owned: false,
      baseColor: "#0033cc",
      stripeColor: "#00ffff"
    },
    {
      id: 3,
      name: "Green Flash",
      price: 30, // Lower price
      owned: false,
      baseColor: "#009900",
      stripeColor: "#ffff00"
    },
    {
      id: 4,
      name: "Yellow Thunder",
      price: 40, // Lower price
      owned: false,
      baseColor: "#ffcc00",
      stripeColor: "#000000"
    },
    {
      id: 5,
      name: "Black Phantom",
      price: 50, // Lower price
      owned: false,
      baseColor: "#111111",
      stripeColor: "#ff0000"
    },
    {
      id: 6,
      name: "Orange Blaze",
      price: 60, // Lower price
      owned: false,
      baseColor: "#ff6600",
      stripeColor: "#ffffff"
    },
  ];

  let selectedCarId = 1;

  // Objects on the road (cacti, coins, power-ups, oil spills, rocks)
  let objects = [];

  // Generate objects at intervals based on speed
  let objectSpawnTimer = 0;
  const spawnInterval = 200; // Increased spawn rate for coins

  // Toggle pause
  function togglePause() {
    paused = !paused;
    if (!paused) {
      lastTimestamp = performance.now();
      gameLoop(lastTimestamp);
    }
  }

  // Generate obstacles/coins/powerups randomly
  function generateObjects() {
    if (paused || gameOver) return;
    const now = performance.now();
    if (now - objectSpawnTimer > spawnInterval) {
      objectSpawnTimer = now;
      const rand = Math.random();
      const lanePositions = [
        roadLeftEdge + roadWidth / 4,
        canvas.width / 2,
        roadRightEdge - roadWidth / 4
      ];
      const x = lanePositions[Math.floor(Math.random() * lanePositions.length)];
      const y = -30;

      if (rand < 0.10) {
        objects.push({ type: "cactus", x, y, width: 30, height: 40 });
      } else if (rand < 0.75) {  // More coins
        objects.push({ type: "coin", x, y, radius: 15 });
      } else if (rand < 0.80) {
        objects.push({ type: "powerUp", x, y, radius: 15 });
      } else if (rand < 0.85) {
        objects.push({ type: "oilSpill", x, y, radius: 20 });
      } else if (rand < 0.90) {
        objects.push({ type: "rock", x, y, radius: 20 });
      }
    }
  }

  // Update all objects positions & check collisions
  function updateObjects(deltaTime) {
    if (paused || gameOver) return;

    for (let i = objects.length - 1; i >= 0; i--) {
      const obj = objects[i];
      obj.y += car.speed * (powerUpActive ? 4 : 1) * deltaTime * 0.06;

      if (obj.y - (obj.height || obj.radius) > canvas.height) {
        objects.splice(i, 1);
        continue;
      }

      // Collision with car
      if (obj.type === "cactus") {
        if (
          car.x + car.width / 2 > obj.x - obj.width / 2 &&
          car.x - car.width / 2 < obj.x + obj.width / 2 &&
          car.y + car.height / 2 > obj.y - obj.height / 2 &&
          car.y - car.height / 2 < obj.y + obj.height / 2
        ) {
          if (!powerUpActive) {
            gameOver = true;
            overlay.style.display = "flex";  // Display the pop-up over the game
          }
        }
      } else if (obj.type === "coin") {
        const distX = Math.abs(car.x - obj.x);
        const distY = Math.abs(car.y - obj.y);
        if (distX < car.width / 2 + obj.radius && distY < car.height / 2 + obj.radius) {
          coins++;
          objects.splice(i, 1);
        }
      } else if (obj.type === "oilSpill") {
        const distX = Math.abs(car.x - obj.x);
        const distY = Math.abs(car.y - obj.y);
        if (distX < car.width / 2 + obj.radius && distY < car.height / 2 + obj.radius) {
          spinCar();
          objects.splice(i, 1);
        }
      } else if (obj.type === "powerUp") {
        const distX = Math.abs(car.x - obj.x);
        const distY = Math.abs(car.y - obj.y);
        if (distX < car.width / 2 + obj.radius && distY < car.height / 2 + obj.radius) {
          activatePowerUp();
          objects.splice(i, 1);
        }
      } else if (obj.type === "rock") {
        const distX = Math.abs(car.x - obj.x);
        const distY = Math.abs(car.y - obj.y);
        if (distX < car.width / 2 + obj.radius && distY < car.height / 2 + obj.radius) {
          // When hitting a rock, bounce back a bit
          car.x -= 30; // Move car back after collision
          objects.splice(i, 1); // Remove the rock
        }
      }
    }
  }

  // Activate power-up (fly over obstacles at high speed)
  function activatePowerUp() {
    powerUpActive = true;
    powerUpTimeLeft = powerUpDuration;
    powerUpBarContainer.style.display = "block";
    car.speed = car.flyingSpeed;
  }

  // Update power-up timer & UI bar
  function updatePowerUp(deltaTime) {
    if (!powerUpActive || paused) return;
    powerUpTimeLeft -= deltaTime;
    if (powerUpTimeLeft <= 0) {
      powerUpActive = false;
      powerUpBarContainer.style.display = "none";
      if (car.speed > car.maxSpeed) car.speed = car.maxSpeed;
    } else {
      const percent = (powerUpTimeLeft / powerUpDuration) * 100;
      powerUpBar.style.width = percent + "%";
    }
  }

  // Function to handle car spinning due to oil spill
  function spinCar() {
    car.isSpinning = true;
    car.rotation = 0;
    car.spinTimer = 0;

    // Spin the car for 1 second
    setTimeout(() => {
      car.isSpinning = false;
    }, 1000);
  }

  // Draw the road with lane lines
  function drawRoad() {
    ctx.fillStyle = "#444";
    ctx.fillRect(roadLeftEdge, 0, roadWidth, canvas.height);

    // Lane lines in center
    ctx.strokeStyle = "white";
    ctx.lineWidth = laneMarkWidth;
    ctx.setLineDash([30, 20]);
    ctx.lineDashOffset -= paused ? 0 : car.speed * 0.5;
    ctx.beginPath();
    ctx.moveTo(canvas.width / 2, 0);
    ctx.lineTo(canvas.width / 2, canvas.height);
    ctx.stroke();
    ctx.setLineDash([]); 
  }

  // Draw the player's car with details (spoiler black sticking out bottom)
  function drawCar() {
    const design = carDesigns.find(c => c.id === selectedCarId);
    const x = car.x;
    const y = car.y;
    const w = car.width;
    const h = car.height;

    ctx.save();

    if (car.isSpinning) {
      car.rotation += car.rotationSpeed;
      ctx.translate(x, y);
      ctx.rotate(car.rotation);
      ctx.translate(-x, -y);
    }

    // Body
    ctx.fillStyle = design.baseColor;
    ctx.fillRect(x - w / 2, y - h / 2, w, h);

    // Stripes
    const stripeWidth = w / 8;
    ctx.fillStyle = design.stripeColor;
    ctx.fillRect(x - stripeWidth / 2, y - h / 2, stripeWidth, h);
    ctx.fillRect(x + stripeWidth * 1.5, y - h / 2, stripeWidth, h);

    // Spoiler (black, bottom/back)
    ctx.fillStyle = "#000";
    ctx.fillRect(x - w / 2 + 6, y + h / 2 - 10, w - 12, 12);

    // Headlights (pale yellow)
    ctx.fillStyle = "#fffacd";
    ctx.fillRect(x - w / 2 + 10, y - h / 2, 12, 8);
    ctx.fillRect(x + w / 2 - 22, y - h / 2, 12, 8);

    // Wheels
    ctx.fillStyle = "#222";
    ctx.fillRect(x - w / 2 - 6, y - h / 4, 8, 16);
    ctx.fillRect(x + w / 2 - 2, y - h / 4, 8, 16);
    ctx.fillRect(x - w / 2 - 6, y + h / 6, 8, 16);
    ctx.fillRect(x + w / 2 - 2, y + h / 6, 8, 16);

    ctx.restore();
  }

  // Draw obstacles, coins, power-ups
  function drawObjects() {
    objects.forEach(obj => {
      if (obj.type === "cactus") {
        ctx.fillStyle = "#228B22";
        ctx.fillRect(obj.x - 15, obj.y - 40, 30, 40);
        ctx.fillRect(obj.x - 25, obj.y - 25, 10, 10);
        ctx.fillRect(obj.x + 15, obj.y - 15, 10, 10);
      } else if (obj.type === "coin") {
        ctx.fillStyle = "#FFD700";
        ctx.beginPath();
        ctx.arc(obj.x, obj.y, obj.radius, 0, Math.PI * 2);
        ctx.fill();
      } else if (obj.type === "powerUp") {
        const gradient = ctx.createRadialGradient(obj.x, obj.y, obj.radius / 4, obj.x, obj.y, obj.radius);
        gradient.addColorStop(0, "#ff00ff");
        gradient.addColorStop(0.5, "#00ffff");
        gradient.addColorStop(1, "#ffff00");
        ctx.fillStyle = gradient;
        ctx.beginPath();
        ctx.arc(obj.x, obj.y, obj.radius, 0, Math.PI * 2);
        ctx.fill();
      } else if (obj.type === "oilSpill") {
        ctx.fillStyle = "#000";
        ctx.beginPath();
        ctx.arc(obj.x, obj.y, obj.radius, 0, Math.PI * 2);
        ctx.fill();
      } else if (obj.type === "rock") {
        ctx.fillStyle = "#808080"; // Rock color
        ctx.beginPath();
        ctx.arc(obj.x, obj.y, obj.radius, 0, Math.PI * 2);
        ctx.fill();
      }
    });
  }

  // Update car position & speed
  function updateCar(deltaTime) {
    if (paused || gameOver) return;

    // Increase speed gradually up to maxSpeed (unless powered up)
    if (!powerUpActive && car.speed < car.maxSpeed) {
      car.speed += car.speedIncreaseRate * deltaTime;
      if (car.speed > car.maxSpeed) car.speed = car.maxSpeed;
    }

    // Left/right movement
    if (keys["ArrowLeft"] || keys["a"]) {
      car.x -= car.turnSpeed;
    }
    if (keys["ArrowRight"] || keys["d"]) {
      car.x += car.turnSpeed;
    }

    // Keep car inside road bounds
    if (car.x - car.width / 2 < roadLeftEdge) {
      car.x = roadLeftEdge + car.width / 2;
    }
    if (car.x + car.width / 2 > roadRightEdge) {
      car.x = roadRightEdge - car.width / 2;
    }
  }

  // Draw HUD updates
  function updateHUD() {
    speedDisplay.textContent = Math.floor(car.speed);
    scoreDisplay.textContent = Math.floor(score);
    coinsDisplay.textContent = coins;
    // Update stats box
    document.getElementById("statsSpeed").textContent = "Speed: " + Math.floor(car.speed) + " MPH";
    document.getElementById("statsScore").textContent = "Score: " + Math.floor(score);
    document.getElementById("statsCoins").textContent = "Coins: " + coins;
  }

  // Reset game
  function resetGame(keepCoins = true) {
    if (!keepCoins) coins = 0;
    score = 0;
    car.speed = 2; // slow start speed
    car.x = canvas.width / 2;
    car.rotation = 0;
    objects = [];
    gameOver = false;
    powerUpActive = false;
    powerUpBarContainer.style.display = "none";
    overlay.style.display = "none";
  }

  // Overlay button handlers
  playAgainBtn.addEventListener("click", () => {
    resetGame(true);
    gameLoop(0);  // Start the game immediately
  });
  goToShopBtn.addEventListener("click", () => {
    overlay.style.display = "none";
    openShop();
  });

  closeShopBtn.addEventListener("click", () => {
    shopScreen.style.display = "none";
    overlay.style.display = "flex"; // show whoops screen again after shop
  });

  // Settings modal
  settingsBtn.addEventListener("click", () => {
    paused = true;  // Pause the game
    settingsModal.style.display = "flex";  // Show settings modal
  });

  closeSettingsBtn.addEventListener("click", () => {
    // Countdown and resume game
    let countdown = 3;
    const countdownInterval = setInterval(() => {
      if (countdown === 0) {
        clearInterval(countdownInterval);
        settingsModal.style.display = "none";
        paused = false;
        gameLoop(performance.now()); // Resume the game
      } else {
        // Update countdown display
        overlay.innerHTML = `<div>Resuming in: ${countdown}</div>`;
        countdown--;
      }
    }, 1000);
  });

  applySettingsBtn.addEventListener("click", () => {
    // Update the turn speed based on slider
    car.turnSpeed = turnSpeedSlider.value;
    turnSpeedValue.textContent = `Turn Speed: ${turnSpeedSlider.value}`;
    // Resume game after applying settings
    let countdown = 3;
    const countdownInterval = setInterval(() => {
      if (countdown === 0) {
        clearInterval(countdownInterval);
        settingsModal.style.display = "none";
        paused = false;
        gameLoop(performance.now()); // Resume the game
      } else {
        // Update countdown display
        overlay.innerHTML = `<div>Resuming in: ${countdown}</div>`;
        countdown--;
      }
    }, 1000);
  });

  // Shop logic
  function openShop() {
    shopScreen.style.display = "flex";
    renderShopCars();
  }

  function renderShopCars() {
    carListDiv.innerHTML = "";
    carDesigns.forEach(carItem => {
      const carDiv = document.createElement("div");
      carDiv.className = "carItem";

      const canvasPreview = document.createElement("canvas");
      canvasPreview.width = 80;
      canvasPreview.height = 120;
      drawCarPreview(canvasPreview, carItem);
      carDiv.appendChild(canvasPreview);

      const name = document.createElement("div");
      name.textContent = carItem.name;
      name.className = "carName";
      carDiv.appendChild(name);

      const price = document.createElement("div");
      price.textContent = "Price: " + carItem.price + " coins";
      price.className = "carPrice";
      carDiv.appendChild(price);

      const button = document.createElement("button");
      if (carItem.owned) {
        button.textContent = (carItem.id === selectedCarId) ? "Selected" : "Select";
        button.disabled = (carItem.id === selectedCarId);
      } else {
        button.textContent = "Buy";
        button.disabled = coins < carItem.price;
      }
      button.className = "buyButton";
      button.addEventListener("click", () => {
        if (carItem.owned) {
          selectedCarId = carItem.id;
          renderShopCars();
        } else if (coins >= carItem.price) {
          coins -= carItem.price;
          carItem.owned = true;
          selectedCarId = carItem.id;
          updateCoinsDisplay();
          renderShopCars();
        }
      });
      carDiv.appendChild(button);

      carListDiv.appendChild(carDiv);
    });
  }

  function drawCarPreview(canvasEl, carItem) {
    const ctxPreview = canvasEl.getContext("2d");
    ctxPreview.clearRect(0, 0, canvasEl.width, canvasEl.height);

    // Body
    ctxPreview.fillStyle = carItem.baseColor;
    ctxPreview.fillRect(15, 25, 50, 90);

    // Stripes
    const stripeWidth = 50 / 8;
    ctxPreview.fillStyle = carItem.stripeColor;
    ctxPreview.fillRect(15 + 20 - stripeWidth / 2, 25, stripeWidth, 90);
    ctxPreview.fillRect(15 + 35, 25, stripeWidth, 90);

    // Spoiler (black)
    ctxPreview.fillStyle = "#000";
    ctxPreview.fillRect(15 + 6, 25 + 90 - 10, 50 - 12, 12);

    // Headlights (pale yellow)
    ctxPreview.fillStyle = "#fffacd";
    ctxPreview.fillRect(15 + 10, 25, 12, 8);
    ctxPreview.fillRect(15 + 50 - 22, 25, 12, 8);

    // Wheels
    ctxPreview.fillStyle = "#222";
    ctxPreview.fillRect(15 - 6, 25 + 22, 8, 16);
    ctxPreview.fillRect(15 + 50 - 2, 25 + 22, 8, 16);
    ctxPreview.fillRect(15 - 6, 25 + 60, 8, 16);
    ctxPreview.fillRect(15 + 50 - 2, 25 + 60, 8, 16);
  }

  function updateCoinsDisplay() {
    coinsDisplay.textContent = coins;
  }

  // Game variables for animation loop
  let lastTimestamp = 0;

  // Main game loop
  function gameLoop(timestamp) {
    if (!lastTimestamp) lastTimestamp = timestamp;
    const deltaTime = timestamp - lastTimestamp;
    lastTimestamp = timestamp;

    if (!paused && !gameOver) {
      updateCar(deltaTime);
      updateObjects(deltaTime);
      updatePowerUp(deltaTime);

      score += car.speed * deltaTime * 0.01;
      generateObjects();
    }

    // Clear and redraw everything
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    drawRoad();
    drawObjects();
    drawCar();
    updateHUD();

    if (!gameOver) {
      requestAnimationFrame(gameLoop);
    }
  }

  // Start game
  resetGame(true);
  showScreen(homeScreen);
  requestAnimationFrame(gameLoop);

})();
```

### Your CSS

```css
/* General body and font settings */
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-color: sandybrown;
      color: #fff;
      text-align: center;
      overflow: hidden;
    }

    /* Title Styling */
    .title {
      font-size: 4rem;
      font-weight: bold;
      text-transform: uppercase;
      background: linear-gradient(45deg, #f39c12, #e74c3c);
      -webkit-background-clip: text;
      color: transparent;
      margin-top: 10vh;
      text-shadow: 2px 2px 5px rgba(0, 0, 0, 0.5);
    }

    /* Screen Layout */
    .screen {
      display: none;
      height: 100vh;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      position: relative;
      overflow: hidden;
    }

    /* Home Screen Button Layout */
    .button-container {
      display: flex;
      justify-content: center;
      gap: 20px;
      margin-top: 20px;
    }

    .game-btn {
      padding: 15px 30px;
      font-size: 1.5rem;
      border: none;
      background-color: #3498db;
      color: white;
      border-radius: 8px;
      cursor: pointer;
    }

    .game-btn:hover {
      background-color: #2980b9;
    }

    /* Car Styling */
    .car {
      position: absolute;
      width: 80px;
      height: 40px;
      background-color: red; /* Base car color */
      border-radius: 5px;
      top: 70%;
      left: 50%;
      transform: translateX(-50%);
      transition: transform 0.5s ease-out;
    }

    .car .headlight {
      position: absolute;
      top: -10px;
      width: 10px;
      height: 10px;
      background-color: yellow;
      border-radius: 50%;
    }

    .car .headlight.left {
      left: -10px;
    }

    .car .headlight.right {
      right: -10px;
    }

    .car .spoiler {
      position: absolute;
      bottom: -10px;
      left: 25%;
      width: 50px;
      height: 10px;
      background-color: black;
      transform: rotate(90deg);
    }

    /* Cactus Styling */
    .cactus {
      position: absolute;
      bottom: 10px;
      width: 40px;
      height: 80px;
      background-color: green;
      border-radius: 5px;
      transform: rotate(30deg);
    }

    .cactus-arm-left {
      position: absolute;
      top: 10px;
      left: -20px;
      width: 20px;
      height: 30px;
      background-color: green;
      border-radius: 5px;
    }

    .cactus-arm-right {
      position: absolute;
      top: 10px;
      right: -20px;
      width: 20px;
      height: 30px;
      background-color: green;
      border-radius: 5px;
    }

    /* Rock Styling */
    .rock {
      position: absolute;
      width: 40px;
      height: 40px;
      background-color: grey;
      border-radius: 50%;
      top: -40px;
    }

    /* Oil Spill Styling (Increased size) */
    .oil-spill {
      position: absolute;
      width: 30px; /* Increased size */
      height: 30px; /* Increased size */
      background-color: black;
      border-radius: 50%;
    }

    /* Coin Styling (Increased size) */
    .coin {
      position: absolute;
      width: 25px; /* Increased size */
      height: 25px; /* Increased size */
      background-color: gold;
      border-radius: 50%;
    }

    /* Coin display */
    .coin-display {
      position: absolute;
      top: 10px;
      right: 10px;
      font-size: 1.5rem;
      color: white;
    }

    /* Rainbow Power Boost */
    .rainbow-bar {
      position: absolute;
      top: 10px;
      left: 0;
      width: 100%;
      height: 10px;
      background: linear-gradient(to right, red, orange, yellow, green, blue, indigo, violet);
      display: none;
    }

    /* Pop-up for collision */
    #overlay {
      position: absolute;
      top: 0;
      left: 0;
      width: 100vw;
      height: 100vh;
      background-color: rgba(0, 0, 0, 0.8);
      color: white;
      display: flex;
      justify-content: center;
      align-items: center;
      font-size: 2rem;
      z-index: 20;
      display: none;
      flex-direction: column;
    }

    #overlay button {
      margin-top: 20px;
      font-size: 1.5rem;
      padding: 10px 20px;
      cursor: pointer;
      border-radius: 5px;
      border: none;
      background-color: #444;
      color: white;
      transition: background-color 0.3s ease;
    }

    #overlay button:hover {
      background-color: #666;
    }

    /* Settings Modal */
    #settingsModal {
      position: fixed;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: rgba(0, 0, 0, 0.8);
      color: white;
      padding: 20px;
      border-radius: 10px;
      display: none;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      z-index: 30;
    }

    #settingsModal .close-btn {
      position: absolute;
      top: 10px;
      right: 10px;
      background-color: red;
      color: white;
      border: none;
      padding: 10px;
      border-radius: 50%;
      font-size: 1.5rem;
      cursor: pointer;
    }

    .gear-btn {
      position: absolute;
      top: 20px;
      right: 20px;
      background-color: #f39c12;
      border: none;
      padding: 10px;
      font-size: 1.5rem;
      cursor: pointer;
      border-radius: 50%;
    }

    /* Stats box */
    #statsBox {
      position: absolute;
      top: 20px;
      right: 20px;
      background: rgba(0, 0, 0, 0.7);
      padding: 10px 20px;
      border-radius: 10px;
      font-size: 1.2rem;
      z-index: 25;
    }

    #statsBox span {
      display: block;
      color: white;
    }
```
