### ISSUE TITLE
SCSS Modulo (x % y) Bug

### ISSUE THREAD

**Issue by emilbayes** [jsfiddle/jsfiddle-issues#351]
The following SCSS does not seem to be parsed correctly over at jsfiddle.net, though it is over at sass-lang.com/try.html:

```scss
    h1 { 
        font-size: 3.375em * 1.1; 
        //The modulo part is not calculated (extra space added for legibility)
        margin:      3.375em * 1.1 % 1        0 1.4em 0;
    }
```
