### ISSUE TITLE
Github repo for fiddle mustn't be bound with file names

### ISSUE THREAD

**Issue by KOLANICH** [jsfiddle/jsfiddle-issues#604]
Now jsfiddle islooking for demo.js, demo.css and demo.html in repo. But I think that the better option is to list them in yml file like
```yaml
html: a.html
js:
 - b.js
 - c.js
css: a.css
```
