### ISSUE TITLE
Result frame label

### ISSUE THREAD

**Issue by Mottie** [jsfiddle/jsfiddle-issues#644]
Sometimes the "Result" label overlays elements with which I need to interact.

It would be great if the result label would hide when the frame gets focus just like the other frames when they get hovered, or this simple css would ignore any interactions:

```css
.window_label { pointer-events: none; }
```
