### ISSUE TITLE
Cannot click down arrow in custom selects.

### ISSUE THREAD

**Issue by JimBobSquarePants** [jsfiddle/jsfiddle-issues#656]
In the new design described at https://medium.com/jsfiddle-updates/the-lifting-cb3c9f216c2f#.jcae4jcpp it is impossible to trigger the select box by clicking the arrow. This can cause confusion leading the user to believe the application is broken.

Adding the following to the selector will fix this. 

``` css
.selectCont label {
    /*Other properties removed for brevity*/
    pointer-events: none; 
}
```
