### ISSUE TITLE
Old version of Sass

### ISSUE THREAD

**Issue by futekov** [jsfiddle/jsfiddle-issues#721]
Hi,

I noticed that some features of sass aren't supported in jsfiddle, it looks like the sass version is a bit old (older than 3.3). One example is that the `random` function doesn't work:

``` scss
.random-integer {
  padding: random(100);
}
```

Additionally, the `@at-root` directive also seems to be missing, this for example doesn't work:

``` scss
.selector {
  color: red;
  @at-root .root-class {
    font-size: 1.2em;
  }
}
```

Is this a known issue and is there a chance it'll get fixed?
